---
# created by Andrei Lupuleasa, December 2018.
- name: 1.Update and upgrade apt packages
  become: true
  apt:
#    name: aptitude
    upgrade: yes
    state: present
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: 2.Install programs
  apt: 
    pkg:
     - curl
     - ftp
     - gcc
     - git
     - man
     - unzip
     - vim
     - wget
     - zip  
     - composer
    state: present
    update_cache: yes
    cache_valid_time: 86400 #One day
    
- name: 3.Install python extensions
  apt: name=python-pexpect update_cache=yes state=latest

- name: 4.Copy Vimrc
  run_once: true
  copy: 
    src: .vimrc
    dest: /home/vagrant/.vimrc

- name: 5.Install vim color schemes
  git:
    repo: git@github.com:flazz/vim-colorschemes.git
    version: master
    dest: /home/vagrant/.vim
    accept_hostkey: yes
  become: no

- name: 6.Copy Bashrc.
  run_once: true
  copy:
    src: .bashrc
    dest: /home/vagrant/.bashrc

# - name: 4.Clone Vimrc
#   git:
#     repo: git@github.com:alupuleasa/vimrc.git
#     version: master
#     dest: /var/www/html/vimrc
#     accept_hostkey: yes
#   # ssh-agent doesn't allow key to pass through remote sudo commands.
#   become: no
#   notify:
#     - move-vimrc