---
# created by Andrei Lupuleasa, December 2018.
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install programs
  apt: 
    pkg:
     - curl
     - ftp
     - gcc
     - git
     - man
     - nano
     - unzip
     - vim
     - wget
     - zip  
    state: present