---
# created by Andrei Lupuleasa, December 2018.
- name: 1.Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: 2.Install programs
  apt: 
    pkg:
     - curl
     - ftp
     - gcc
     - git
     - man
     - nano
     - unzip
     - vim
     - wget
     - zip  
     - composer
    state: present
    
- name: 3.Install python extensions
  apt: name=python-pexpect update_cache=yes state=latest