---
# created by Andrei Lupuleasa, December 2019.
- name: Install MySQL
  apt: 
    name: '{{ item }}'
    update_cache: yes 
    cache_valid_time: 3600 
    state: present
  become: true
  with_items:
   - 'python-mysqldb'
   - 'mysql-server'

- name: Copy config
  copy: 
    src: .my.cnf 
    dest: ~/.my.cnf 
    owner: root
    mode: 0644
  become: true

- name: Start the MySQL service
  become: true
  service: 
    name: mysql 
    state: started
    enabled: true

- name: Update mysql root password for all root accounts
  become: true
  mysql_user: 
    name: root 
    host: '{{ item }}'
    password: ''
    login_user: root
    login_password: ''
    check_implicit_admin: yes
    priv: '*.*:ALL,GRANT'
  with_items:
   - '%'
   - '127.0.0.1'
   - '::1'
   - 'localhost' 

- name: Update firewall
  become: true
  command: ufw allow mysql
  tags: once