---
- name: 1.Install PHP packages
  become: true
  apt:
    name:
     - php7.2
     - php7.2-dev
     - php7.2-cli
     - php7.2-common
     - php7.2-fpm
     - php7.2-gd
     - php7.2-intl
     - php7.2-json
     - php7.2-mbstring
     - php7.2-opcache
     - php7.2-pdo
     - php7.2-soap
     - php7.2-xml
     - php7.2-xmlrpc
     - php7.2-xdebug
     - php7.2-memcached
     - php7.2-dom
     - php7.2-curl
     - php7.2-bcmath
     - php7.2-apcu
     - php-amqp
     - php-pecl-http
     - php-pear
     - mcrypt
     - libmcrypt4
     - libmcrypt-dev
     - libtomcrypt-dev
     - libtomcrypt1
    state: latest
    update_cache: yes
    cache_valid_time: 86400 #One day
  notify:
   - restart-apache2
  tags: once

- name: 2.Update  Pecl
  become: true
  command: pecl channel-update pecl.php.net
  tags: once

- name: 3.Install PHP packages with Pecl
  become:  true
  command: pecl install mcrypt-1.0.1
  notify:
   - restart-apache2
  tags: once
  ignore_errors: yes

- name: 4.Write mcrypt.ini
  copy:
    dest: '{{item}}'
    content: 'extension=/usr/lib/php/20170718/mcrypt.so'
  with_items:
   - '/etc/php/7.2/cli/conf.d/mcrypt.ini'
   - '/etc/php/7.2/apache2/conf.d/mcrypt.ini'
  notify:
   - restart-apache2
  tags: once

- name: 5.Write into index.php file
  copy:
    dest: /var/www/html/index.php
    content: '<?php phpinfo(); ?>'
  tags: once

- name: 6.Install Couchbase packages with Pecl
  become:  true
  command: pecl install couchbase
  notify:
   - restart-apache2
  tags: once
  ignore_errors: yes

- name: 8.Enable Couchbase
  copy:
    src: couchbase.ini
    dest: '{{item}}'
  with_items:
   - '/etc/php/7.2/apache2/conf.d/couchbase.ini'
   - '/etc/php/7.2/cli/conf.d/couchbase.ini'
  notify:
   - restart-apache2
  tags: once

- name: 9. Restart Apache2
  service: name=apache2 state=restarted

# - name: 9. Restart Apache2
#   service: name=apache2 state=restarted

#  /etc/php/7.2/apache2/conf.d/mcrypt.ini
#  /etc/php/7.2/cli/conf.d/mcrypt.ini

# - name: 3.Enable mcrypt
#   become: true
#   command: phpenmod mcrypt 
#   notify:
#    - restart-apache2

# - name: 3.Enable mcrypt
#   become: true
#   shell:
#    - bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/cli/conf.d/mcrypt.ini"
#    - bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/apache2/conf.d/mcrypt.ini"
#   notify:
#    - restart-apache2
