---
- name: Install PHP packages
  become: true
  apt:
    name:
     - php7.2
     - php7.2-cli 
     - php7.2-common 
     - php7.2-fpm 
     - php7.2-gd 
     - php7.2-intl 
     - php7.2-json 
     - php7.2-mbstring 
     # - php7.2-mcrypt 
     - php7.2-mysqlnd 
     - php7.2-opcache 
     - php7.2-pdo 
     # - php7.2-pear
     # - php7.2-pecl-uploadprogress 
     # - php7.2-pecl-zip 
     - php7.2-soap 
     - php7.2-xml 
     - php7.2-xmlrpc
     - php7.2-xdebug 
    state: latest
  notify:
   - restart apache2
   
- name: Write into index.php file
  copy:
    dest: /var/www/html/index.php
    content: '<?php phpinfo(); ?>' 