---
- name: 1.Install PHP packages
  become: true
  apt:
    name:
     - php7.2
     - php7.2-dev
     - php7.2-cli 
     - php7.2-common 
     - php7.2-fpm 
     - php7.2-gd 
     - php7.2-intl 
     - php7.2-json 
     - php7.2-mbstring 
     - php7.2-opcache 
     - php7.2-pdo 
     - php7.2-soap 
     - php7.2-xml 
     - php7.2-xmlrpc
     - php7.2-xdebug 
     - php7.2-memcached 
     - php7.2-dom 
     - php7.2-curl 
     - php7.2-bcmath
     - php7.2-apcu
     - php-amqp
     - php-pecl-http
     - php-pear
     - mcrypt
     - libmcrypt4
     - libmcrypt-dev 
     - libtomcrypt-dev
     - libtomcrypt1
    state: latest
  notify:
   - restart-apache2

# - name: 2.Install PHP packages with Pecl
#   become: true
#   command: pecl install mcrypt-1.0.1
#   run_once: true

# - name: 3.Enable mcrypt
#   become: true
#   shell:
#    - bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/cli/conf.d/mcrypt.ini"
#    - bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/apache2/conf.d/mcrypt.ini"
#   notify:
#    - restart-apache2  

# - name: 3.Enable mcrypt
#   become: true
#   command: phpenmod mcrypt 
#   notify:
#    - restart-apache2

- name: 4.Write into index.php file
  copy:
    dest: /var/www/html/index.php
    content: '<?php phpinfo(); ?>' 