---
- name: 1.Install Gdebi latest
  apt: name=gdebi-core update_cache=yes state=latest cache_valid_time=86400
  tags: once
  
- name: 2.Download Couchbase server
  get_url:
    url: https://packages.couchbase.com/releases/5.0.1/couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb
    dest: /home/vagrant/couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb
  tags: once

- name: 3.Copy couchbase list
  copy: 
    src: couchbase.list
    dest: /etc/apt/sources.list.d/couchbase.list
  tags: once

- name: 4.Add Couchbase Key
  apt_key:
    url: http://packages.couchbase.com/ubuntu/couchbase.key
    state: present
  tags: once

- name: 5.Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    state: present
  tags: once

- name: 6. Install Couchbase Libs 
  apt: 
    pkg:
     - libcouchbase-dev
     - libcouchbase2-bin
     - build-essential
    state: latest
  ignore_errors: yes
  tags: once

- name: 7.Update firewall
  become: true
  command: ufw allow from any to any port 369,8091:8094,9100:9105,9998,9999,11209:11211,11214,11215,18091:18093,21100:21299 proto tcp
  tags: once


# - name: 4.0.Transfer the script
#   copy: src=add_key.sh dest=/home/vagrant/add_key.sh mode=0777

# - name: 4.1.Add Couchbase Key
#   become: true
#   command: sh add_key.sh

# - name: 4.Add Couchbase Key
#   apt_key:
#     url: http://packages.couchbase.com/ubuntu/couchbase.key
#     keyring: 

# - name: 4.Add Couchbase Key
#   become: true
#   command: wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add - 
#   tags: once



#- name: 3.Install Couchbase server
#  become: true
#  expect:
#    command: gdebi /home/vagrant/couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb
#    responses:
#      'Do you want to install the software package\? \[y/N\]': 'y'

# - name: 4.Download Couchbase
#   get_url:
#     url: http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb
#     dest: /home/vagrant/couchbase-release-1.0-4-amd64.deb

# - name: 5.Install Couchbase
#   become: true
#   expect:
#     command: gdpkg -i couchbase-release-1.0-4-amd64.deb
#     responses: 
#       'Do you want to install the software package\? \[y/N\]': 'y'



# - name: 5.Stop Couchbase Server
  # become: true
  # command: systemctl stop couchbase-server 
  # tags: once

# - name: 6.Disable Couchbase Server
#   become: true
#   command: systemctl disable couchbase-server 
#   tags: once