---
- name: 1.Install Gdebi latest
  apt: name=gdebi-core update_cache=yes state=latest cache_valid_time=86400
  
- name: 2.Download Couchbase server
  get_url:
    url: https://packages.couchbase.com/releases/5.0.1/couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb
    dest: /home/vagrant/couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb

#- name: 3.Install Couchbase server
#  become: true
#  expect:
#    command: gdebi /home/vagrant/couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb
#    responses:
#      'Do you want to install the software package\? \[y/N\]': 'y'

# - name: 4.Download Couchbase
#   get_url:
#     url: http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb
#     dest: /home/vagrant/couchbase-release-1.0-4-amd64.deb

# - name: 5.Install Couchbase
#   become: true
#   expect:
#     command: gdpkg -i couchbase-release-1.0-4-amd64.deb
#     responses: 
#       'Do you want to install the software package\? \[y/N\]': 'y'

# - name: 6. Lib libcouchbase-dev 
#   apt: 
#     name:
#      -libcouchbase-dev 
#      -libcouchbase2-bin 
#      -build-essential
#     state: latest

- name: 4.Update firewall
  become: true
  command: ufw allow from any to any port 369,8091:8094,9100:9105,9998,9999,11209:11211,11214,11215,18091:18093,21100:21299 proto tcp

- name: 5.Stop Couchbase Server
  become: true
  command: systemctl stop couchbase-server 

- name: 6.Disable Couchbase Server
  become: true
  command: systemctl disable couchbase-server 